Default test_framework to rspec
This is because we were getting the following error when generating a worker from a rails engine

/Users/banta/.rvm/gems/ruby-3.0.2@rails/gems/sidekiq-6.2.1/lib/generators/sidekiq/worker_generator.rb:53:in `test_framework': undefined method `config' for nil:NilClass (NoMethodError)
	from /Users/banta/.rvm/gems/ruby-3.0.2@rails/gems/sidekiq-6.2.1/lib/generators/sidekiq/worker_generator.rb:19:in `create_test_file'
	from /Users/banta/.rvm/gems/ruby-3.0.2@rails/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	from /Users/banta/.rvm/gems/ruby-3.0.2@rails/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
.....
.....
.....